# Generated by Django 4.2.23 on 2025-08-03 20:33

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('elder_id', models.CharField(default=api.models.generate_elderly_id, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default=datetime.date(1998, 3, 24))),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.CharField(default=api.models.generate_guardian_id, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default=datetime.date(1998, 3, 24))),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('med_id', models.CharField(default=api.models.generate_med_id, max_length=20, unique=True)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('NOT_TAKEN', 'Not Taken')], default='NOT_TAKEN', max_length=20)),
                ('elderly', models.ForeignKey(db_column='elderly_id', on_delete=django.db.models.deletion.CASCADE, to='api.elderly')),
                ('guardian', models.ForeignKey(db_column='guardian_id', on_delete=django.db.models.deletion.CASCADE, to='api.guardian')),
            ],
        ),
        migrations.AddField(
            model_name='elderly',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elderlies', to='api.guardian'),
        ),
        migrations.AddField(
            model_name='elderly',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
